FROM node:22-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci --production=false

COPY . ./
RUN npm run build

FROM node:22-alpine AS runtime
WORKDIR /app

COPY --from=builder /app/package*.json ./
RUN npm ci --production

COPY --from=builder /app/dist ./dist

ENV PORT={{ config.ecs.container_port }}
EXPOSE {{ config.ecs.container_port }}

CMD ["node", "dist/index.js"]
