FROM golang:1.24-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/server .

FROM alpine:3.21 AS runtime
RUN apk --no-cache add ca-certificates
WORKDIR /app

COPY --from=builder /app/server ./

ENV PORT={{ config.ecs.container_port }}
EXPOSE {{ config.ecs.container_port }}

ENTRYPOINT ["./server"]
